require "delegate"
require "forwardable"

require "minitest"

require "expectorant/version"
require "expectorant/expector"
require "expectorant/resolver"
require "expectorant/asserter"
require "expectorant/assertion/proximal"
require "expectorant/assertion/equalizer"
require "expectorant/assertion/existential"
require "expectorant/assertion/collector"
require "expectorant/assertion/typetastic"
require "expectorant/assertion/matcher"
require "expectorant/assertion/comparitor"
require "expectorant/assertion/cambiarse"
